Repository team-trillion/yamuzip, pull requests merged in 2024-04, with the labels that each got.

#39 [#22] 도비 중복 신청 해결
  src/main/java/team/trillion/yamuzip/config/SecurityConfig.java
  src/main/java/team/trillion/yamuzip/dobby/model/dao/DobbyRegistMapper.java
  src/main/java/team/trillion/yamuzip/dobby/model/service/DobbyRegistService.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/controller/DobbyController.java
  src/main/java/team/trillion/yamuzip/dobby/regist/controller/RegistController.java
  src/main/java/team/trillion/yamuzip/dobby/regist/model/dao/RegistMapper.java
  src/main/java/team/trillion/yamuzip/dobby/regist/model/dto/RegistDTO.java
  src/main/java/team/trillion/yamuzip/dobby/regist/model/service/RegistService.java
  src/main/resources/mappers/dobby/RegistMapper.xml
  src/main/resources/templates/dobby/regist.html
  src/main/resources/templates/dobby/registPage.html
Labels: ✨기능

#44 [#31] 회원관리, 서비스관리, 신규신청관리 detail
  dbscript/insert.sql
  src/main/java/team/trillion/yamuzip/admin/controller/CalcController.java
  src/main/java/team/trillion/yamuzip/admin/controller/DobbyController.java
  src/main/java/team/trillion/yamuzip/admin/controller/ServiceController.java
  src/main/java/team/trillion/yamuzip/admin/model/dao/CalcMapper.java
  src/main/java/team/trillion/yamuzip/admin/model/dao/DobbyMapper.java
  src/main/java/team/trillion/yamuzip/admin/model/dto/CalcDTO.java
  src/main/java/team/trillion/yamuzip/admin/model/dto/CalcDetailDTO.java
  src/main/java/team/trillion/yamuzip/admin/model/dto/CalcMonthlyDTO.java
  src/main/java/team/trillion/yamuzip/admin/model/dto/ServiceDTO.java
  src/main/java/team/trillion/yamuzip/admin/model/service/CalcService.java
  src/main/java/team/trillion/yamuzip/admin/model/service/DobbyService.java
  src/main/resources/mappers/admin/CalcMapper.xml
  src/main/resources/mappers/admin/DobbyMapper.xml
  src/main/resources/static/js/chart.js
  src/main/resources/templates/admin/calc/detail.html
  src/main/resources/templates/admin/calc/monthly.html
  src/main/resources/templates/admin/dobby/list.html
  src/main/resources/templates/admin/order/list.html
  src/main/resources/templates/admin/service/list.html
  src/main/resources/templates/admin/user/list.html
Labels: ✨기능

#50 [#46] 월별정산 엑셀파일 다운로드 기능 구현
  build.gradle
  src/main/java/team/trillion/yamuzip/admin/controller/ExcelController.java
  src/main/java/team/trillion/yamuzip/admin/model/dto/CalcDTO.java
  src/main/java/team/trillion/yamuzip/admin/model/service/CalcService.java
  src/main/java/team/trillion/yamuzip/config/EmailConfig.java
  src/main/resources/templates/admin/calc/monthly.html
Labels: ✨기능

#54 [#42] 도비 주문내역 관리 구현
  src/main/java/team/trillion/yamuzip/YamuzipApplication.java
  src/main/java/team/trillion/yamuzip/common/exception/CancelFailedException.java
  src/main/java/team/trillion/yamuzip/common/scheduler/SchedulerMapper.java
  src/main/java/team/trillion/yamuzip/common/scheduler/SchedulerService.java
  src/main/java/team/trillion/yamuzip/common/scheduler/dto/OrderDTO.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/controller/DobbyController.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/controller/OrderController.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/dao/OrderMapper.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/dto/OrderCountDTO.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/dto/OrderDTO.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/service/OrderService.java
  src/main/java/team/trillion/yamuzip/order/controller/OrderController.java
  src/main/java/team/trillion/yamuzip/order/model/dto/OrderRejectDTO.java
  src/main/java/team/trillion/yamuzip/order/model/dto/OrderResultDTO.java
  src/main/java/team/trillion/yamuzip/order/model/service/PaymentService.java
  src/main/resources/application.yml
  src/main/resources/mappers/dobby/OrderMapper.xml
  src/main/resources/mappers/scheduler/SchedulerMapper.xml
  src/main/resources/messages/messages_ko_KR.Properties
  src/main/resources/static/css/style.css
  src/main/resources/templates/dobby/order.html
  src/main/resources/templates/dobby/orderDetail.html
  src/main/resources/templates/dobby/orderReject.html
  src/main/resources/templates/layout/fragments/default/head.html
  src/main/resources/templates/layout/fragments/default/script.html
  src/main/resources/templates/order/success.html
Labels: ✨기능

#52 [#22] 도비 신청, 회원 도비 프로필 등록 구현
  src/main/java/team/trillion/yamuzip/common/scheduler/dao/SchedulerMapper.java
  src/main/java/team/trillion/yamuzip/common/scheduler/service/SchedulerService.java
  src/main/java/team/trillion/yamuzip/config/SecurityConfig.java
  src/main/java/team/trillion/yamuzip/config/WebConfig.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/controller/DobbyController.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/controller/ModifyController.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/controller/OrderController.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/dao/ModifyMapper.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/dto/ModifyDTO.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/dto/WorkdayDTO.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/service/ModifyService.java
  src/main/java/team/trillion/yamuzip/dobby/regist/controller/RegistController.java
  src/main/java/team/trillion/yamuzip/login/controller/UserController.java
  src/main/java/team/trillion/yamuzip/login/model/dao/UserMapper.java
  src/main/java/team/trillion/yamuzip/user/mypage/controller/ModifyController.java
  src/main/java/team/trillion/yamuzip/user/mypage/controller/MypageController.java
  src/main/java/team/trillion/yamuzip/user/mypage/model/dao/ModifyMapper.java
  src/main/java/team/trillion/yamuzip/user/mypage/model/dto/ModifyDTO.java
  src/main/java/team/trillion/yamuzip/user/mypage/model/service/ModifyService.java
  src/main/java/team/trillion/yamuzip/user/mypage/model/service/OrderService.java
  src/main/resources/application.yml
  src/main/resources/mappers/dobby/ModifyMapper.xml
  src/main/resources/mappers/dobby/RegistMapper.xml
  src/main/resources/mappers/login/UserMapper.xml
  src/main/resources/mappers/scheduler/SchedulerMapper.xml
  src/main/resources/mappers/user/mypage/ModifyMapper.xml
  src/main/resources/mappers/user/mypage/OrderMapper.xml
  src/main/resources/templates/dobby/calc.html
  src/main/resources/templates/dobby/cs.html
  src/main/resources/templates/dobby/main.html
  src/main/resources/templates/dobby/order.html
  src/main/resources/templates/dobby/orderDetail.html
  src/main/resources/templates/dobby/profile.html
  src/main/resources/templates/dobby/profilePage.html
  src/main/resources/templates/dobby/regist.html
  src/main/resources/templates/dobby/registPage.html
  src/main/resources/templates/dobby/service.html
  src/main/resources/templates/layout/fragments/dobby/profile.html
  src/main/resources/templates/layout/fragments/user/profile.html
  src/main/resources/templates/login/profile.html
  src/main/resources/templates/user/mypage/cancelDetail.html
  src/main/resources/templates/user/mypage/cancelList.html
  src/main/resources/templates/user/mypage/cs.html
  src/main/resources/templates/user/mypage/main.html
  src/main/resources/templates/user/mypage/orderDetail.html
  src/main/resources/templates/user/mypage/orderList.html
  src/main/resources/templates/user/mypage/profile.html
  src/main/resources/templates/user/mypage/review.html
  src/main/resources/templates/user/mypage/service.html
Labels: ✨기능, 🎨HTML/CSS

#56 [#51] 신규도비신청 관리 기능 구현
  src/main/java/team/trillion/yamuzip/admin/controller/DobbyApplyController.java
  src/main/java/team/trillion/yamuzip/admin/model/dao/DobbyApplyMapper.java
  src/main/java/team/trillion/yamuzip/admin/model/dto/DobbyApplyDTO.java
  src/main/java/team/trillion/yamuzip/admin/model/service/DobbyApplyService.java
  src/main/java/team/trillion/yamuzip/login/controller/UserController.java
  src/main/resources/mappers/admin/DobbyApplyMapper.xml
  src/main/resources/templates/admin/apply/list.html
  src/main/resources/templates/admin/calc/monthly.html
Labels: ✨기능

#58 [#53] 도비 계좌 등록
  src/main/java/team/trillion/yamuzip/dobby/mypage/controller/AccountController.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/controller/DobbyController.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/controller/ModifyController.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/dao/AccountMapper.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/dao/ModifyMapper.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/dto/WorkdayDTO.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/service/AccountService.java
  src/main/resources/application.yml
  src/main/resources/templates/dobby/calc.html
  src/main/resources/templates/dobby/profile.html
  src/main/resources/templates/dobby/profilePage.html
  src/main/resources/templates/layout/user.html
Labels: ✨기능, 🎨HTML/CSS

#61 [#53] 도비 계좌 등록 구현
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/dto/AccountDTO.java
  src/main/resources/mappers/dobby/AccountMapper.xml
Labels: ✨기능

#62 [#55] 공지사항 게시판
  src/main/java/team/trillion/yamuzip/config/SecurityConfig.java
  src/main/java/team/trillion/yamuzip/notice/controller/NoticeController.java
  src/main/java/team/trillion/yamuzip/notice/model/dao/NoticeMapper.java
  src/main/java/team/trillion/yamuzip/notice/model/dto/NoticeDTO.java
  src/main/java/team/trillion/yamuzip/notice/model/service/NoticeService.java
  src/main/resources/mappers/notice/NoticeMapper.xml
  src/main/resources/templates/notice/detail.html
  src/main/resources/templates/notice/modify.html
  src/main/resources/templates/notice/notice.html
  src/main/resources/templates/notice/regist.html
Labels: ✨기능

#64 [#53] 도비 영업일 구현
  src/main/java/team/trillion/yamuzip/dobby/mypage/controller/AccountController.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/controller/DobbyController.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/controller/ModifyController.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/controller/OrderController.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/dao/ModifyMapper.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/service/ModifyService.java
  src/main/java/team/trillion/yamuzip/user/mypage/controller/MypageController.java
  src/main/java/team/trillion/yamuzip/user/mypage/model/dao/MypageMapper.java
  src/main/java/team/trillion/yamuzip/user/mypage/model/dao/RecentMapper.java
  src/main/java/team/trillion/yamuzip/user/mypage/model/service/MypageService.java
  src/main/resources/mappers/dobby/ModifyMapper.xml
  src/main/resources/mappers/user/mypage/RecentMapper.xml
  src/main/resources/templates/dobby/profile.html
  src/main/resources/templates/user/mypage/profile.html
Labels: ✨기능, 🎨HTML/CSS

#66 [#65] 비밀번호 찾기 기능 구현
  src/main/java/team/trillion/yamuzip/login/controller/FindPwdController.java
  src/main/java/team/trillion/yamuzip/login/controller/MailController.java
  src/main/java/team/trillion/yamuzip/login/controller/UserController.java
  src/main/java/team/trillion/yamuzip/login/model/dao/FindMailServiceinter.java
  src/main/java/team/trillion/yamuzip/login/model/dao/MailServiceInter.java
  src/main/java/team/trillion/yamuzip/login/model/dao/UserMapper.java
  src/main/java/team/trillion/yamuzip/login/model/dto/MailDTO.java
  src/main/java/team/trillion/yamuzip/login/model/service/FindPwdResetMail.java
  src/main/java/team/trillion/yamuzip/login/model/service/RegisterMail.java
  src/main/java/team/trillion/yamuzip/login/model/service/UserService.java
  src/main/resources/mappers/login/FindMailMapper.xml
  src/main/resources/mappers/login/UserMapper.xml
  src/main/resources/templates/login/findId.html
  src/main/resources/templates/login/findPwd.html
  src/main/resources/templates/login/regist.html
Labels: ✨기능

#68 #48 서비스 수정 삭제 기능 완료
  build.gradle
  src/main/java/team/trillion/yamuzip/common/exceptionHandler/GlobalExceptionHandler.java
  src/main/java/team/trillion/yamuzip/login/controller/UserController.java
  src/main/java/team/trillion/yamuzip/service/controller/ServiceController.java
  src/main/java/team/trillion/yamuzip/service/model/dao/ServiceMapper.java
  src/main/java/team/trillion/yamuzip/service/model/dto/ImageDTO.java
  src/main/java/team/trillion/yamuzip/service/model/service/ServiceService.java
  src/main/resources/mappers/service/ServiceMapper.xml
  src/main/resources/templates/service/serviceDetail.html
  src/main/resources/templates/service/serviceModify.html
  src/main/resources/templates/service/serviceRegist.html
Labels: ✨기능

#70 [#63] 고객센터 문의 게시판 구현
  src/main/java/team/trillion/yamuzip/common/exception/ReadAccessDeniedException.java
  src/main/java/team/trillion/yamuzip/common/exceptionHandler/GlobalExceptionHandler.java
  src/main/java/team/trillion/yamuzip/cs/controller/CSController.java
  src/main/java/team/trillion/yamuzip/cs/model/dao/CSMapper.java
  src/main/java/team/trillion/yamuzip/cs/model/dto/CSDTO.java
  src/main/java/team/trillion/yamuzip/cs/model/service/CSService.java
  src/main/resources/mappers/cs/CSMapper.xml
  src/main/resources/templates/cs/cs.html
  src/main/resources/templates/cs/detail.html
  src/main/resources/templates/cs/modify.html
  src/main/resources/templates/cs/regist.html
  src/main/resources/templates/dobby/order.html
  src/main/resources/templates/layout/fragments/default/head.html
  src/main/resources/templates/user/mypage/cancelList.html
  src/main/resources/templates/user/mypage/orderList.html
Labels: ✨기능

#73 [#53] ModifyTmpDTO 파일
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/dto/ModifyTmpDTO.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/dto/ServiceDTO.java
  src/main/java/team/trillion/yamuzip/user/mypage/model/dto/ServiceDTO.java
Labels: ✨기능

#71 [#60] 회원 및 도비 상세조회
  src/main/java/team/trillion/yamuzip/admin/controller/DobbyController.java
  src/main/java/team/trillion/yamuzip/admin/controller/UserController.java
  src/main/java/team/trillion/yamuzip/admin/model/dao/DobbyMapper.java
  src/main/java/team/trillion/yamuzip/admin/model/dao/UserMapper.java
  src/main/java/team/trillion/yamuzip/admin/model/dto/DobbyCalcDTO.java
  src/main/java/team/trillion/yamuzip/admin/model/dto/DobbyDTO.java
  src/main/java/team/trillion/yamuzip/admin/model/dto/DobbyServiceDTO.java
  src/main/java/team/trillion/yamuzip/admin/model/dto/UserDTO.java
  src/main/java/team/trillion/yamuzip/admin/model/dto/UserOrderDTO.java
  src/main/java/team/trillion/yamuzip/admin/model/dto/UserReviewDTO.java
  src/main/java/team/trillion/yamuzip/admin/model/service/DobbyService.java
  src/main/java/team/trillion/yamuzip/admin/model/service/UserService.java
  src/main/java/team/trillion/yamuzip/common/enums/UserAuth.java
  src/main/java/team/trillion/yamuzip/user/mypage/model/dto/ReviewDTO.java
  src/main/resources/mappers/admin/DobbyMapper.xml
  src/main/resources/mappers/admin/OrderMapper.xml
  src/main/resources/mappers/admin/UserMapper.xml
  src/main/resources/templates/admin/dobby/detail.html
  src/main/resources/templates/admin/dobby/detailCalc.html
  src/main/resources/templates/admin/dobby/detailService.html
  src/main/resources/templates/admin/dobby/list.html
  src/main/resources/templates/admin/service/list.html
  src/main/resources/templates/admin/user/detail.html
  src/main/resources/templates/admin/user/detailOrder.html
  src/main/resources/templates/admin/user/detailReview.html
  src/main/resources/templates/admin/user/list.html
Labels: ✨기능

#76 [#74] 서비스 숨김 및 삭제
  .gitignore
  src/main/java/team/trillion/yamuzip/admin/controller/ServiceController.java
  src/main/java/team/trillion/yamuzip/admin/controller/UserController.java
  src/main/java/team/trillion/yamuzip/admin/model/dao/ServiceMapper.java
  src/main/java/team/trillion/yamuzip/admin/model/dto/ServiceDTO.java
  src/main/java/team/trillion/yamuzip/admin/model/service/ServiceService.java
  src/main/java/team/trillion/yamuzip/common/enums/ServiceStatus.java
  src/main/resources/application.yml
  src/main/resources/mappers/admin/ServiceMapper.xml
  src/main/resources/templates/admin/service/list.html
Labels: ✨기능

#80 [#79] 메인 화면에 공지사항 출력
  src/main/java/team/trillion/yamuzip/main/controller/MainController.java
  src/main/java/team/trillion/yamuzip/notice/model/dao/NoticeMapper.java
  src/main/java/team/trillion/yamuzip/notice/model/service/NoticeService.java
  src/main/resources/mappers/notice/NoticeMapper.xml
  src/main/resources/templates/main.html
Labels: ✨기능

#82 [#78] 회원 정지 자동 해제 버그 수정
  src/main/java/team/trillion/yamuzip/admin/controller/UserController.java
  src/main/java/team/trillion/yamuzip/admin/model/service/UserService.java
  src/main/resources/templates/admin/user/banList.html
Labels: 🐞버그

#87 [#83] 관리자 주문 취소 기능 구현
  src/main/java/team/trillion/yamuzip/admin/controller/OrderController.java
  src/main/java/team/trillion/yamuzip/admin/model/dto/OrderDetailDTO.java
  src/main/resources/templates/admin/order/cancel.html
  src/main/resources/templates/admin/order/cancle.html
  src/main/resources/templates/admin/order/detail.html
Labels: ✨기능

#90 [#89] 도비 마이페이지 구현
  src/main/java/team/trillion/yamuzip/dobby/mypage/controller/CalculateController.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/controller/DobbyController.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/controller/ServiceController.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/dao/CalculateMapper.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/dao/ServiceMapper.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/dto/CalculateDTO.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/dto/ServiceDTO.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/dto/ServiceStatusDTO.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/service/CalculateService.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/service/ModifyService.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/service/ServiceService.java
  src/main/resources/mappers/dobby/CalculateMapper.xml
  src/main/resources/mappers/dobby/ModifyMapper.xml
  src/main/resources/mappers/dobby/ServiceMapper.xml
  src/main/resources/templates/dobby/calc.html
  src/main/resources/templates/dobby/profilePage.html
  src/main/resources/templates/dobby/service.html
  src/main/resources/templates/layout/fragments/dobby/profile.html
Labels: ✨기능, 🎨HTML/CSS

#91 [#81] 고객센터 문의 답변 기능 구현
  src/main/java/team/trillion/yamuzip/cs/controller/CSController.java
  src/main/java/team/trillion/yamuzip/cs/controller/CSReplyController.java
  src/main/java/team/trillion/yamuzip/cs/model/dao/CSMapper.java
  src/main/java/team/trillion/yamuzip/cs/model/dao/CSReplyMapper.java
  src/main/java/team/trillion/yamuzip/cs/model/dto/CSReplyDTO.java
  src/main/java/team/trillion/yamuzip/cs/model/service/CSReplyService.java
  src/main/java/team/trillion/yamuzip/cs/model/service/CSService.java
  src/main/resources/mappers/cs/CSReplyMapper.xml
  src/main/resources/templates/cs/cs.html
  src/main/resources/templates/cs/detail.html
Labels: ✨기능

#92 [#84] 관리자 고객센터 문의
  src/main/java/team/trillion/yamuzip/admin/controller/CSAController.java
  src/main/java/team/trillion/yamuzip/admin/controller/CSController.java
  src/main/java/team/trillion/yamuzip/admin/controller/CsController.java
  src/main/java/team/trillion/yamuzip/admin/model/dao/CSAMapper.java
  src/main/java/team/trillion/yamuzip/admin/model/dao/CSMapper.java
  src/main/java/team/trillion/yamuzip/admin/model/dto/CSADTO.java
  src/main/java/team/trillion/yamuzip/admin/model/dto/CSDTO.java
  src/main/java/team/trillion/yamuzip/admin/model/service/CSAService.java
  src/main/java/team/trillion/yamuzip/admin/model/service/CSService.java
  src/main/resources/mappers/admin/CSMapper.xml
  src/main/resources/mappers/service/ServiceMapper.xml
  src/main/resources/templates/admin/cs/delete.html
  src/main/resources/templates/admin/cs/detail.html
  src/main/resources/templates/admin/cs/list.html
  src/main/resources/templates/admin/cs/modify.html
  src/main/resources/templates/admin/cs/regist.html
Labels: ✨기능

#94 [#93] 관리자 고객센터 문의 답변
  src/main/java/team/trillion/yamuzip/admin/controller/CSController.java
  src/main/java/team/trillion/yamuzip/admin/controller/CSReplyController.java
  src/main/java/team/trillion/yamuzip/admin/model/dao/CSMapper.java
  src/main/java/team/trillion/yamuzip/admin/model/dao/CSReplyMapper.java
  src/main/java/team/trillion/yamuzip/admin/model/dto/CSReplyDTO.java
  src/main/java/team/trillion/yamuzip/admin/model/service/CSReplyService.java
  src/main/java/team/trillion/yamuzip/admin/model/service/CSService.java
  src/main/resources/mappers/admin/CSMapper.xml
  src/main/resources/mappers/admin/CSReplyMapper.xml
  src/main/resources/templates/admin/cs/detail.html
  src/main/resources/templates/admin/cs/list.html
  src/main/resources/templates/admin/cs/modify.html
  src/main/resources/templates/admin/cs/regist.html
Labels: ✨기능

#97 [#88] 찜 기능 추가
  src/main/java/team/trillion/yamuzip/service/controller/LikeController.java
  src/main/java/team/trillion/yamuzip/service/controller/ServiceController.java
  src/main/java/team/trillion/yamuzip/service/model/dao/ServiceMapper.java
  src/main/java/team/trillion/yamuzip/service/model/dto/OrderDTO.java
  src/main/java/team/trillion/yamuzip/service/model/dto/ServiceDTO.java
  src/main/java/team/trillion/yamuzip/service/model/dto/WishDTO.java
  src/main/java/team/trillion/yamuzip/service/model/service/ServiceService.java
  src/main/resources/mappers/service/ServiceMapper.xml
  src/main/resources/templates/service/serviceDetail.html
  src/main/resources/templates/service/serviceList.html
  src/main/resources/templates/service/serviceRegist.html
Labels: ✨기능

#100 [#99] 마이페이지 주문 상태 조회
  src/main/java/team/trillion/yamuzip/dobby/mypage/controller/DobbyController.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/controller/ModifyController.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/dao/ModifyMapper.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/dao/OrderStatusMapper.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/dto/OrderStatusDTO.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/service/ModifyService.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/service/OrderStatusService.java
  src/main/java/team/trillion/yamuzip/user/mypage/controller/MypageController.java
  src/main/java/team/trillion/yamuzip/user/mypage/model/dao/OrderStatusMapper.java
  src/main/java/team/trillion/yamuzip/user/mypage/model/dto/OrderStatusDTO.java
  src/main/java/team/trillion/yamuzip/user/mypage/model/service/OrderStatusService.java
  src/main/resources/mappers/dobby/ModifyMapper.xml
  src/main/resources/mappers/dobby/OrderStatusMapper.xml
  src/main/resources/mappers/user/mypage/ModifyMapper.xml
  src/main/resources/mappers/user/mypage/OrderStatusMapper.xml
  src/main/resources/templates/dobby/calc.html
  src/main/resources/templates/dobby/main.html
  src/main/resources/templates/dobby/profile.html
  src/main/resources/templates/dobby/registPage.html
  src/main/resources/templates/dobby/service.html
  src/main/resources/templates/user/mypage/main.html
Labels: ✨기능, 🎨HTML/CSS

#102 [#101] 마이페이지 찜한 서비스 조회
  src/main/java/team/trillion/yamuzip/user/mypage/controller/MypageController.java
  src/main/java/team/trillion/yamuzip/user/mypage/controller/WishController.java
  src/main/java/team/trillion/yamuzip/user/mypage/model/dao/WishMapper.java
  src/main/java/team/trillion/yamuzip/user/mypage/model/dto/WishDTO.java
  src/main/java/team/trillion/yamuzip/user/mypage/model/service/WistService.java
  src/main/resources/mappers/login/UserMapper.xml
  src/main/resources/mappers/user/mypage/WishMapper.xml
  src/main/resources/templates/layout/fragments/dobby/content.html
  src/main/resources/templates/layout/fragments/user/content.html
  src/main/resources/templates/user/mypage/service.html
Labels: ✨기능, 🎨HTML/CSS

#103 [#101] 도비 등록 모달창 변경
  src/main/resources/templates/dobby/registPage.html
Labels: 🎨HTML/CSS

#104 [#95] 전체 주문 내역 검색 옵션 추가
  src/main/java/team/trillion/yamuzip/admin/controller/OrderController.java
  src/main/java/team/trillion/yamuzip/admin/model/dao/OrderMapper.java
  src/main/java/team/trillion/yamuzip/admin/model/dto/OrderDTO.java
  src/main/java/team/trillion/yamuzip/admin/model/service/OrderService.java
  src/main/resources/mappers/admin/OrderMapper.xml
  src/main/resources/static/js/order.js
  src/main/resources/templates/admin/calc/monthly.html
  src/main/resources/templates/admin/category/select.html
  src/main/resources/templates/admin/dobby/detail.html
  src/main/resources/templates/admin/order/list.html
  src/main/resources/templates/admin/user/detailOrder.html
  src/main/resources/templates/layout/fragments/default/header.html
  src/main/resources/templates/main.html
Labels: ✨기능, 🎨HTML/CSS

#106 #98 오타 수정
  src/main/java/team/trillion/yamuzip/service/controller/ServiceController.java
  src/main/java/team/trillion/yamuzip/service/model/dto/CsDTO.java
  src/main/java/team/trillion/yamuzip/service/model/dto/OrderDTO.java
  src/main/java/team/trillion/yamuzip/service/model/dto/ReviewDTO.java
  src/main/java/team/trillion/yamuzip/service/model/service/ServiceService.java
  src/main/resources/mappers/service/ServiceMapper.xml
  src/main/resources/templates/dobby/service.html
  src/main/resources/templates/service/serviceDetail.html
  src/main/resources/templates/service/serviceList.html
Labels: ✨기능

#109 Feat: #108 오더 링크 오류
  src/main/java/team/trillion/yamuzip/order/controller/OrderController.java
  src/main/java/team/trillion/yamuzip/service/controller/ServiceController.java
  src/main/resources/mappers/order/OrderMapper.xml
  src/main/resources/templates/service/serviceDetail.html
Labels: ⚙설정

#114 Feat:[#113]- 도비 마이페이지에 링크 입력
  src/main/java/team/trillion/yamuzip/service/controller/ServiceController.java
  src/main/resources/mappers/dobby/ModifyMapper.xml
  src/main/resources/mappers/service/ServiceMapper.xml
  src/main/resources/templates/dobby/service.html
  src/main/resources/templates/service/serviceDetail.html
  src/main/resources/templates/service/serviceList.html
Labels: ✨기능

#111 [#101] 도비 마이페이지 서비스 등록
  src/main/java/team/trillion/yamuzip/user/mypage/controller/MypageController.java
  src/main/resources/mappers/dobby/ModifyMapper.xml
  src/main/resources/templates/dobby/profilePage.html
  src/main/resources/templates/dobby/service.html
Labels: ✨기능

#112 [#105] 관리자페이지 기능 수정
  src/main/java/team/trillion/yamuzip/admin/controller/OrderController.java
  src/main/java/team/trillion/yamuzip/common/paging/Pagenation.java
  src/main/java/team/trillion/yamuzip/common/paging/SelectCriteria.java
  src/main/resources/mappers/admin/DobbyMapper.xml
  src/main/resources/mappers/admin/OrderMapper.xml
  src/main/resources/mappers/service/ServiceMapper.xml
  src/main/resources/static/js/order.js
  src/main/resources/templates/admin/calc/detail.html
  src/main/resources/templates/admin/calc/monthly.html
  src/main/resources/templates/admin/dobby/detailCalc.html
  src/main/resources/templates/admin/dobby/detailService.html
  src/main/resources/templates/admin/order/list.html
  src/main/resources/templates/admin/service/list.html
  src/main/resources/templates/admin/user/detailOrder.html
  src/main/resources/templates/login/login.html
  src/main/resources/templates/login/regist.html
Labels: 🐞버그, ✨기능, 🎨HTML/CSS

#115 [#110] 도비 테이블 생성
  src/main/java/team/trillion/yamuzip/dobby/mypage/controller/ModifyController.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/dao/ModifyMapper.java
  src/main/java/team/trillion/yamuzip/dobby/mypage/model/service/ModifyService.java
  src/main/resources/mappers/dobby/ModifyMapper.xml
Labels: ✨기능

#116 Feat: 주문내역 조회 링크 수정
  src/main/resources/templates/admin/dashboard/acc.html
  src/main/resources/templates/layout/fragments/admin/sidebar.html
Labels: ✨기능

#117 Feat: 관리자 사이드바 링크 수정
  src/main/resources/templates/admin/apply/list.html
  src/main/resources/templates/admin/calc/detail.html
  src/main/resources/templates/admin/calc/monthly.html
  src/main/resources/templates/admin/dashboard/acc.html
  src/main/resources/templates/admin/order/detail.html
  src/main/resources/templates/admin/order/list.html
  src/main/resources/templates/admin/service/list.html
  src/main/resources/templates/layout/fragments/admin/sidebar.html
Labels: 🎨HTML/CSS
