Repository team-trillion/yamuzip, pull requests merged in 2024-03, with the labels that each got.

#7 [#2] 주문 기능 구현
  src/main/java/team/trillion/yamuzip/order/controller/OrderController.java
  src/main/java/team/trillion/yamuzip/order/model/dao/OrderMapper.java
  src/main/java/team/trillion/yamuzip/order/model/dto/CategoryDTO.java
  src/main/java/team/trillion/yamuzip/order/model/dto/DobbyDTO.java
  src/main/java/team/trillion/yamuzip/order/model/dto/ImageDTO.java
  src/main/java/team/trillion/yamuzip/order/model/dto/OptionDTO.java
  src/main/java/team/trillion/yamuzip/order/model/dto/OrderDTO.java
  src/main/java/team/trillion/yamuzip/order/model/dto/ServiceDTO.java
  src/main/java/team/trillion/yamuzip/order/model/dto/WorkdayDTO.java
  src/main/java/team/trillion/yamuzip/order/model/service/OrderService.java
  src/main/resources/application.yml
  src/main/resources/mappers/order/OrderMapper.xml
  src/main/resources/static/css/rome.css
  src/main/resources/static/js/popper.min.js
  src/main/resources/static/js/rome.js
  src/main/resources/templates/order/order.html
Labels: ✨기능

#13 [#10] 주문 완료 페이지 구현
  src/main/java/team/trillion/yamuzip/common/exception/OrderFailedException.java
  src/main/java/team/trillion/yamuzip/common/exceptionHandler/GlobalExceptionHandler.java
  src/main/java/team/trillion/yamuzip/order/controller/OrderController.java
  src/main/java/team/trillion/yamuzip/order/model/dao/OrderMapper.java
  src/main/java/team/trillion/yamuzip/order/model/dto/OrderResultDTO.java
  src/main/java/team/trillion/yamuzip/order/model/service/OrderService.java
  src/main/resources/mappers/order/OrderMapper.xml
  src/main/resources/static/css/rome.css
  src/main/resources/static/css/style.css
  src/main/resources/templates/common/error.html
  src/main/resources/templates/layout/fragments/head.html
  src/main/resources/templates/layout/fragments/script.html
  src/main/resources/templates/order/error.html
  src/main/resources/templates/order/order.html
  src/main/resources/templates/order/payment.html
  src/main/resources/templates/order/success.html
Labels: ✨기능

#14 [#11] 결제 방식 추가
  src/main/resources/templates/order/payment.html
Labels: ✨기능

#17 [#4] 서비스 페이지/상세 페이지 조회 기능
  build.gradle
  src/main/java/team/trillion/yamuzip/main/controller/MainController.java
  src/main/java/team/trillion/yamuzip/service/controller/ServiceController.java
  src/main/java/team/trillion/yamuzip/service/model/dao/ServiceMapper.java
  src/main/java/team/trillion/yamuzip/service/model/dto/CsDTO.java
  src/main/java/team/trillion/yamuzip/service/model/dto/CsRepDTO.java
  src/main/java/team/trillion/yamuzip/service/model/dto/DobbyDTO.java
  src/main/java/team/trillion/yamuzip/service/model/dto/ImageDTO.java
  src/main/java/team/trillion/yamuzip/service/model/dto/OptionDTO.java
  src/main/java/team/trillion/yamuzip/service/model/dto/ReviewDTO.java
  src/main/java/team/trillion/yamuzip/service/model/dto/ServiceDTO.java
  src/main/java/team/trillion/yamuzip/service/model/dto/UserDTO.java
  src/main/java/team/trillion/yamuzip/service/model/service/ServiceService.java
  src/main/resources/mappers/ServiceMapper.xml
  src/main/resources/static/css/style.css
  src/main/resources/static/images/설치_2.png
  src/main/resources/static/images/수리2.webp
  src/main/resources/templates/layout/fragments/head.html
  src/main/resources/templates/search/serviceList.html
  src/main/resources/templates/service/serviceInfo.html
Labels: ✨기능

#19 [#18] 빈 이름 중복 문제 해결
  src/main/java/team/trillion/yamuzip/YamuzipApplication.java
  src/main/java/team/trillion/yamuzip/config/CustomBeanNameGenerator.java
  src/main/java/team/trillion/yamuzip/config/MybatisConfig.java
  src/main/resources/mappers/UserMapper.xml
Labels: 🐞버그

#21 [#5] 로그인 및 회원가입
  build.gradle
  src/main/java/team/trillion/yamuzip/auth/controller/AuthController.java
  src/main/java/team/trillion/yamuzip/auth/model/CustomUser.java
  src/main/java/team/trillion/yamuzip/auth/service/AuthService.java
  src/main/java/team/trillion/yamuzip/config/SecurityConfig.java
  src/main/java/team/trillion/yamuzip/main/controller/MainController.java
  src/main/java/team/trillion/yamuzip/user/controller/UserController.java
  src/main/java/team/trillion/yamuzip/user/dao/UserMapper.java
  src/main/java/team/trillion/yamuzip/user/dto/UserDTO.java
  src/main/java/team/trillion/yamuzip/user/model/Authority.java
  src/main/java/team/trillion/yamuzip/user/service/UserService.java
  src/main/resources/application.yml
  src/main/resources/mappers/UserMapper.xml
  src/main/resources/mappers/pom.xml
  src/main/resources/messages/messages_ko_KR.Properties
  src/main/resources/static/css/style.css
  src/main/resources/templates/admin/admin.html
  src/main/resources/templates/layout/fragments/header.html
  src/main/resources/templates/user/findId.html
  src/main/resources/templates/user/findPwd.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/regist.html
Labels: ✨기능

#25 [#24] 로그인 에러 해결
  src/main/java/team/trillion/yamuzip/auth/model/CustomUser.java
  src/main/java/team/trillion/yamuzip/auth/service/AuthService.java
  src/main/java/team/trillion/yamuzip/config/SecurityConfig.java
  src/main/java/team/trillion/yamuzip/user/controller/UserController.java
  src/main/java/team/trillion/yamuzip/user/dto/UserDTO.java
  src/main/java/team/trillion/yamuzip/user/model/Authority.java
  src/main/resources/mappers/UserMapper.xml
  src/main/resources/pom.xml
  src/main/resources/templates/layout/dobby/header.html
  src/main/resources/templates/layout/fragments/header.html
  src/main/resources/templates/layout/user/header.html
  src/main/resources/templates/user/login.html
Labels: 🐞버그

#26 [#11] 결제 정보에 인증 객체 추가
  src/main/java/team/trillion/yamuzip/user/dto/UserDTO.java
  src/main/resources/templates/order/payment.html
Labels: ✨기능

#28 [#27] header.html 인증객체 적용 및 mypage 디렉토리로 이동
  src/main/resources/templates/layout/fragments/header.html
  src/main/resources/templates/layout/mypage.html
  src/main/resources/templates/layout/mypage/footer.html
  src/main/resources/templates/layout/mypage/head.html
  src/main/resources/templates/layout/mypage/header.html
  src/main/resources/templates/layout/mypage/profile.html
  src/main/resources/templates/layout/mypage/script.html
  src/main/resources/templates/mypage/main.html
Labels: ✨기능

#30 [#12] 관리자 회원, 신청, 서비스 조회
  dbscript/create-table.sql
  src/main/java/team/trillion/yamuzip/admin/controller/DobbyApplyController.java
  src/main/java/team/trillion/yamuzip/admin/model/dao/DobbyApplyMapper.java
  src/main/java/team/trillion/yamuzip/admin/model/dto/DobbyApplyDTO.java
  src/main/java/team/trillion/yamuzip/admin/model/dto/ServiceDTO.java
  src/main/java/team/trillion/yamuzip/admin/model/service/DobbyApplyService.java
  src/main/java/team/trillion/yamuzip/main/controller/MainController.java
  src/main/resources/mappers/admin/DobbyApplyMapper.xml
  src/main/resources/mappers/admin/ServiceMapper.xml
  src/main/resources/templates/admin/apply/list.html
  src/main/resources/templates/admin/dashboard/dashboard.html
  src/main/resources/templates/admin/service/list.html
Labels: ✨기능, 🎨HTML/CSS

#32 [#12] js 오류수정 & apply detail 조회
  src/main/java/team/trillion/yamuzip/admin/controller/DobbyApplyController.java
  src/main/java/team/trillion/yamuzip/admin/model/service/DobbyApplyService.java
  src/main/resources/mappers/admin/DobbyApplyMapper.xml
  src/main/resources/templates/admin/apply/list.html
  src/main/resources/templates/admin/user/list.html
  src/main/resources/templates/layout/admin/head.html
  src/main/resources/templates/layout/admin/script.html
  src/main/resources/templates/layout/fragments/head.html
  src/main/resources/templates/layout/fragments/script.html
Labels: 🐞버그, ✨기능, ⚙설정

#36 Thymeleaf layout 경로수정
  src/main/java/team/trillion/yamuzip/admin/controller/DobbyController.java
  src/main/java/team/trillion/yamuzip/admin/model/dao/DobbyMapper.java
  src/main/java/team/trillion/yamuzip/admin/model/dto/CSADTO.java
  src/main/java/team/trillion/yamuzip/admin/model/dto/CSDTO.java
  src/main/java/team/trillion/yamuzip/admin/model/dto/CalcDTO.java
  src/main/java/team/trillion/yamuzip/admin/model/dto/CategoryDTO.java
  src/main/java/team/trillion/yamuzip/admin/model/dto/DobbyApplyDTO.java
  src/main/java/team/trillion/yamuzip/admin/model/dto/DobbyDTO.java
  src/main/java/team/trillion/yamuzip/admin/model/dto/OrderDTO.java
  src/main/java/team/trillion/yamuzip/admin/model/dto/ServiceDTO.java
  src/main/java/team/trillion/yamuzip/admin/model/dto/UserDTO.java
  src/main/java/team/trillion/yamuzip/admin/model/service/DobbyService.java
  src/main/resources/mappers/admin/DobbyMapper.xml
  src/main/resources/templates/admin/dobby/detail.html
  src/main/resources/templates/layout/admin.html
  src/main/resources/templates/layout/admin/head.html
  src/main/resources/templates/layout/admin/header.html
  src/main/resources/templates/layout/admin/script.html
  src/main/resources/templates/layout/dobby.html
  src/main/resources/templates/layout/dobby/footer.html
  src/main/resources/templates/layout/fragments/admin/content.html
  src/main/resources/templates/layout/fragments/admin/sidebar.html
  src/main/resources/templates/layout/fragments/default/content.html
  src/main/resources/templates/layout/fragments/default/footer.html
  src/main/resources/templates/layout/fragments/default/head.html
  src/main/resources/templates/layout/fragments/default/header.html
  src/main/resources/templates/layout/fragments/default/script.html
  src/main/resources/templates/layout/fragments/dobby/content.html
  src/main/resources/templates/layout/fragments/dobby/profile.html
  src/main/resources/templates/layout/fragments/footer.html
  src/main/resources/templates/layout/fragments/head.html
  src/main/resources/templates/layout/fragments/header.html
  src/main/resources/templates/layout/fragments/script.html
  src/main/resources/templates/layout/fragments/user/content.html
  src/main/resources/templates/layout/fragments/user/profile.html
  src/main/resources/templates/layout/mypage/footer.html
  src/main/resources/templates/layout/mypage/head.html
  src/main/resources/templates/layout/mypage/header.html
  src/main/resources/templates/layout/mypage/script.html
  src/main/resources/templates/layout/user.html
  src/main/resources/templates/mypage/cs.html
  src/main/resources/templates/mypage/main.html
  src/main/resources/templates/mypage/order.html
  src/main/resources/templates/mypage/review.html
  src/main/resources/templates/mypage/service.html
Labels: ⚙설정

#33 Refactor: 디렉토리 구조 변경
  src/main/java/team/trillion/yamuzip/auth/model/CustomUser.java
  src/main/java/team/trillion/yamuzip/auth/service/AuthService.java
  src/main/java/team/trillion/yamuzip/common/enums/OrderStatus.java
  src/main/java/team/trillion/yamuzip/common/enums/PayStatus.java
  src/main/java/team/trillion/yamuzip/common/paging/Pagenation.java
  src/main/java/team/trillion/yamuzip/common/paging/SelectCriteria.java
  src/main/java/team/trillion/yamuzip/login/controller/UserController.java
  src/main/java/team/trillion/yamuzip/login/dao/UserMapper.java
  src/main/java/team/trillion/yamuzip/login/dto/UserDTO.java
  src/main/java/team/trillion/yamuzip/login/model/Authority.java
  src/main/java/team/trillion/yamuzip/login/service/UserService.java
  src/main/java/team/trillion/yamuzip/user/mypage/controller/MypageController.java
  src/main/java/team/trillion/yamuzip/user/mypage/controller/OrderController.java
  src/main/java/team/trillion/yamuzip/user/mypage/model/dao/OrderMapper.java
  src/main/java/team/trillion/yamuzip/user/mypage/model/dto/OrderDTO.java
  src/main/java/team/trillion/yamuzip/user/mypage/model/dto/OrderDetailDTO.java
  src/main/java/team/trillion/yamuzip/user/mypage/model/service/OrderService.java
  src/main/resources/mappers/UserMapper.xml
  src/main/resources/mappers/user/mypage/OrderMapper.xml
  src/main/resources/pom.xml
  src/main/resources/templates/login/findId.html
  src/main/resources/templates/login/findPwd.html
  src/main/resources/templates/login/login.html
  src/main/resources/templates/login/regist.html
  src/main/resources/templates/user/mypage/cs.html
  src/main/resources/templates/user/mypage/main.html
  src/main/resources/templates/user/mypage/order.html
  src/main/resources/templates/user/mypage/orderDetail.html
  src/main/resources/templates/user/mypage/profile.html
  src/main/resources/templates/user/mypage/review.html
  src/main/resources/templates/user/mypage/service.html
Labels: ⚙설정

#34 feat : dobby regist 작업 중
  src/main/java/team/trillion/yamuzip/dobby/controller/DobbyController.java
  src/main/java/team/trillion/yamuzip/dobby/controller/DobbyRegistController.java
  src/main/java/team/trillion/yamuzip/dobby/model/dao/DobbyRegistMapper.java
  src/main/java/team/trillion/yamuzip/dobby/model/dto/DobbyRegistDTO.java
  src/main/java/team/trillion/yamuzip/dobby/model/service/DobbyRegistService.java
  src/main/resources/mappers/dobby/RegistMapper.xml
  src/main/resources/templates/dobby/profile.html
  src/main/resources/templates/dobby/regist.html
  src/main/resources/templates/dobby/registPage.html
  src/main/resources/templates/layout/fragments/default/header.html
Labels: ✨기능, 🎨HTML/CSS
